### ISSUE TITLE
[Meta] Change list

### ISSUE THREAD

**Issue by AriaMoradi** [KaiserBh/tachiyomi#3]
## upstream PR changes
- [x] Rename backup stuff now that its being used by both sync and backup
- [x] Put sync and backup in the same screen
- [x] Prequel PR containing only database related changes
- [x] Wait for `favoriteModifiedAt` implementation and then split db changes into another PR

## Downstream fork changes
- [x] Refactor: remove code duplication from e76a35a87702337e173ab51ec6d7c5facd8a6b49
- [x] Implement `favoriteModifiedAt`
    - [ ] Auto purge rule
- [x] Refactor syncPrefs
    - [x] add prefix to SyncYomi syncPref keys to future proof them
    - [x] Remove `SyncDevice`
- [ ] WebDAV sync service
- [x] refactor backup and restore logic, we shouldn't just add a flag
    
## SyncYomi changes
- [x] fix user authorization bugs
- [x] fix ArMor's sql bug
- [x] remove device data
